<?php
/**
 * Created by Thai Fintech.
 * User: Jessy Chan
 * Date: 2017/12/14
 * Time: 10:03
 */

namespace app\api\lib\exception;


use Exception;
use think\exception\Handle;
use think\Request;

class ExceptionHandler extends Handle {

    private $code;
    private $msg;
    private $errorCode;

    public function render(Exception $e){

        if($e instanceof BaseException){
            $this->code      = $e->code;
            $this->msg       = $e->msg;
            $this->errorCode = $e->errorCode;
        }else{
            $this->code      = 500;
            $this->msg       = '服务器内部错误';
            $this->errorCode = 999;
        }

        $request = Request::instance();

        $result = [
            'msg' => $this->msg,
            'errorCode' => $this->errorCode,
            'url'       => $request->url()
        ];
        return json($result, $this->code);
//        return parent::render($e); // TODO: Change the autogenerated stub
    }
}